### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by JuhQ** [lopossumi/askare-front#1]
Huomioita

Sivuston käytettävyydestä
  - rekisteröintilomake ei näytä virhettä
    - virheeni oli liian lyhyt salasana, olisi hyvä varmasti näyttää salasanan minimiehdot?
  - rekisteröitymisen jälkeen olisi kiva jos sivusto kirjaisi minut automaattisesti sisälle
  - pystyin luomaan listan tyhjällä nimellä
    - pystyin lisäämään listaan itemin tyhjillä arvoilla
  - sivuston ui on kiva

Frontend
  - services hakemistossa http kutsut try/catch blockien sisällä, tosi jees!
  - reduxia käytetty hyvin
  - koodi on selkeää
  - react komponenttien sulkutagi kannattaa olla aina samalla rivillä kuin avaustagi, eli
    ```
    <Button
      color='green'
      icon='user'
      content='Sign me up!'
      labelPosition='left'
      onClick={this.handleOpen} />
    ```
    kannattaisi muuttaa muotoon
    ```
    <Button
      color='green'
      icon='user'
      content='Sign me up!'
      labelPosition='left'
      onClick={this.handleOpen}
    />
    ```
      - tällöin on huomattavasti helpompi koodia vilkuilemalla nähdä minne komponentti päättyy
  - kun komponenttirivit muuttuvat pitkiksi, niitä kannattaa splitata useamalle riville. 80 merkin pituus on hyvä raja
    ```
    <Dropdown placeholder='Pick a color' fluid selection options={colorOptions} onChange={this.handleDropdown}/>
    ```
    muotoon

    ```
    <Dropdown
      placeholder='Pick a color'
      fluid
      selection
      options={colorOptions}
      onChange={this.handleDropdown}
    />
    ```
      - tällöin propertyt on heti helpompi bongata

Backend
  - controllers/taskList.js tiedostossa olisi kiva nähdä middlewareja
  - koodi on lyhyt ja ytimekäs

Oikein jees :)

**Comment by lopossumi** [comment]
Moi JuhQ, kiitokset palautteesta! 

Projekti eteni viime viikonlopun aikana melko paljon, ja suuri osa edellämainituista on fiksattu.
* Rekisteröitymisessä validointia ja viestejä (client- ja server-side) sekä login-kenttien täyttö
* Käyttäjä voi siirrellä taskeja voi siirrellä listojen välillä; tyhjiä ei pitäisi voida luoda (task content saa tosin olla tyhjä, ja listoista irrallisia taskeja voi luoda)
* Käyttäjä voi muuttaa tietojaan. Username lowercapsataan tarkistuksissa, mutta tallennetaan myös alkuperäisessä kirjoitusasussa (jotta User1 ja usEr1 eivät ole molemmat sallittuja); sekä usernamea että sähköpostiosoitetta voi muuttaa, käyttäjäID ja identicon ovat muuttumattomat
* Käyttäjä voi poistaa itsensä
* UI:ta paranneltu varsinkin mobiilikäyttöä ajatellen, työtä riittää
* GDPR: Käyttöehdot / tietosuoja lisätty rekisteröitymisen yhteyteen
* Aika paljon refaktorointia - kahteen kertaan kirjoitettua koodia abstrahoitu frontin puolella, ja reducereita käytetty jo hieman fiksummin
* middlewareja käytetty hitusen tehokkaammin tokenin lukemisessa
* Uuden käyttäjän luomisen yhteydessä luodaan lista, jossa edes hieman käyttöohjetta.
* Tietoturvaongelmia korjattu

Seuraavassa vaiheessa:
* Käyttäjien haku (opt-in)
* Unohtuneen salasanan vaihto (sähköposti + lyhytaikainen token)
* Admin view + tietokantaoperaatiot
* Hakutoiminto (taskien suodatus otsikon ja sisällön perusteella - listarakenne katoaa haun ajaksi)
* GDPR: Omien tietojen exporttaus, kuten käyttäjäehdoissa lupaillaan
* Lisää validointia (kenttien minimi- ja maksimipituudet)
* Refaktorointia: yhdenmukaisempi nimeäminen, tiedostojen järjestely, johdonmukaisempi reducer/service -työnjako

Tämänhetkinen tuotantoversio alkaa kelvata itselleni jo itseensä liittyvään projektinhallintaan, mikä on mukavaa. :)
